config/routes.rb
Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  get "/dashboard/" => "dashboard#index"

  resources :manage_users, only: [:index, :show, :edit, :update], path: '/dashboard/users'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # custom path for displaying records created by signed-in user
  get '/citations/mine' => 'bibliographies#mine'

  # custom path for displaying records containing pending suggesitions
  get '/citations/terms/suggestions' => 'bibliographies#suggestions'

  # custom path for displaying all records
  # this is effectively the same as /citations  
  get '/citations/all' => 'bibliographies#index'

  # piggybacking on citationterms search controller for citation records
  get '/citations/search' => 'term_search#index'

  resources :staticpages

  get '/api/updated' => 'api#list_updated'
  get '/api/all' => 'api#all'

  get "/featuredrecords/all" => 'featuredrecords#load_all', as: 'featuredrecords_all'
  resources :featuredrecords

  namespace :about, path: '/about' do
    # root goes to dedicated home page record
    get "/" => '/staticpages#load_page', slug: :home, as: 'home_page'
    get "/:slug" => '/staticpages#load_page', as: 'page'
  end

  # get paths like "/citations/1"
  resources :bibliographies, path: '/citations' do
    root to: redirect('/citations/mine')
    resources :comments
    resources :standard_identifiers
    #resources :languages
    resources :reviewed_components
    resources :publishers
    resources :publish_places
    resources :dissertation_universities
    resources :series_multimedias
    resources :tags
    resources :subject_suggestions
    resources :location_suggestions
    resources :entity_suggestions
    resources :period_suggestions
    resources :language_suggestions
    resources :journal_suggestions
    resources :thesis_types_suggestions
    resources :authors
    resources :editors
    resources :book_editors
    resources :author_of_reviews
    resources :performers
    resources :bib, only: [:index], controller: "bib", action: "raw"
    resources :mla, only: [:index], controller: "bib", action: "mla"
    resources :chicago, only: [:index], controller: "bib", action: "chicago"
    resources :turabian, only: [:index], controller: "bib", action: "turabian"
  end

  # get paths like "/citations/terms/subject/1"
  namespace :citationterms, path: '/citations/terms' do
    resources :subjects, path: 'subjects' do
      get 'references', on: :member
    end
    resources :entities, path: 'jesuits' do
      get 'references', on: :member
    end
    resources :periods, path: 'centuries' do
      get 'references', on: :member
    end
    resources :locations, path: 'locations' do
      get 'references', on: :member
    end
    resources :languages, path: 'languages' do
      get 'references', on: :member
    end
    resources :people, path: 'people' do
      get 'references', on: :member
    end
    resources :journals, path: 'journals' do
      get 'references', on: :member
    end
    resources :thesis_types, path: 'thesis_types' do
      get 'references', on: :member
    end
    get 'search' => 'term_search#index'
  end

  get '/form_partial/:id/:reference_type' => 'bibliographies#form_partial'


  namespace :terms do
    root to: redirect('/')
    resources :entities, only: [:index], path: 'jesuits'
    resources :locations, only: [:index], path: 'locations'
    resources :subjects, only: [:index], path: 'subjects'
    resources :periods, only: [:index], path: 'centuries'
  end


  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  Blacklight::Marc.add_routes(self)
  # custom action for root
  # root to: "catalog#index"
  root to: "catalog#job_home"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end
  devise_for :users, controllers: { registrations: 'registrations' }
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/manage_users_controller.rb
class ManageUsersController < ApplicationController
    protect_from_forgery with: :exception
    #load_and_authorize_resource

    before_action :require_login
    before_action :authenticate_user!
    before_action :set_user, only: [:show, :edit, :update]
    before_action :generate_roles_current_user_can_manage

    layout 'bibliography'

    def index
        authorize! :read, 'ManageUsers', :message => "Unable to load this page."

        if !@roles_current_user_can_manage.empty?
            @role_message = "current user role: #{current_user.role}"
            @users_grid = initialize_grid(User,
                conditions:      {role: @roles_current_user_can_manage},
                order:           'users.name',
                order_direction: 'asc'
            )
        end
    end

    def show
    end

    def edit
        @role_options = []
        if !@user.nil?
            # generate the array of roles for the edit screen options list
            @role_options = generate_role_options
        end

        @role_options
    end

    def update
        # copy over user_params into user_attributes so we can alter it
        user_attributes = user_params

        # HACK check that the new role submitted is included in @roles_current_user_can_manage
        if is_selected_role_valid?(@roles_current_user_can_manage, user_attributes[:role])
            if @user.update(user_attributes)
                respond_to do |format|
                    format.html { redirect_to manage_user_path(@user), notice: 'User was successfully updated.' }
                    format.json { render :show, status: :ok, location: @user }
                end
            else
                respond_to do |format|
                    # HACK reset all values for re-rendering
                    @old_user = @user.clone
                    set_user
                    @user.errors.merge!(@old_user.errors)

                    @role_options = generate_role_options
                    
                    format.html { render :edit }
                    format.json { render json: @user.errors, status: :unprocessable_user }
                end
            end
        else
             # TODO move this logic into model if possible
             # HACK reset all values for re-rendering
             @old_user = @user.clone
             set_user
             @user.errors.merge!(@old_user.errors)
 
             @role_options = generate_role_options
             respond_to do |format|
                 format.html { render :edit }
                 format.json { render json: @user.errors, status: :unprocessable_user }
             end
        end
    end

    private
        def set_user
            begin
                authorize! :read, 'ManageUsers', :message => "Unable to load this page."

                grab_user = User.find(params[:id])

                # make sure we can access the selected user account.
                # this is based on cancancan ability settings.
                if can? :manage, 'Associates' and grab_user.is_role? "associate_editor"
                    @user = grab_user
                elsif can? :manage, 'Assistants' and grab_user.is_role? "assistant_editor"
                    @user = grab_user
                elsif can? :manage, 'Correspondents' and grab_user.is_role? "correspondent"
                    @user = grab_user
                elsif can? :manage, 'Standards' and grab_user.is_role? "standard"
                    @user = grab_user
                else 
                    @user = nil
                end
            rescue ActiveRecord::RecordNotFound => e
                @user = nil
            end
        end

        # loop through list of roles the current_user can manage and generate an options list for the edit form
        def generate_role_options
            user_role_index = User::USER_ROLES.index(@user.role.to_sym)

            select_roles = []

            @roles_current_user_can_manage.each do |role|
                my_role_index = User::USER_ROLES.index(role)
                label = "#{role.to_s.sub("_", " ").capitalize} #{get_role_rank_string(user_role_index, my_role_index)}"
                select_roles << [label, role]
            end

            select_roles
        end

        # check cancancan abilitites to determine which roles the current_user can access
        def generate_roles_current_user_can_manage 
            @roles_current_user_can_manage = []
            @role_descriptions = {}

            if can? :manage, 'Associates'
                @roles_current_user_can_manage << :associate_editor
                @role_descriptions[:associate_editor] = User::ASSOCIATE_EDITOR_ROLE_DESCRIPTION
            end
            if can? :manage, 'Assistants'
                @roles_current_user_can_manage << :assistant_editor
                @role_descriptions[:assistant_editor] = User::ASSISTANT_EDITOR_ROLE_DESCRIPTION
            end
            if can? :manage, 'Correspondents'
                @roles_current_user_can_manage << :correspondent
                @role_descriptions[:correspondent] = User::CORRESPONDENT_ROLE_DESCRIPTION
            end
            if can? :manage, 'Standards'
                @roles_current_user_can_manage << :standard
                @role_descriptions[:standard] = User::STANDARD_ROLE_DESCRIPTION
            end
            #if can? :manage, 'Guests'
            #    @roles_current_user_can_manage << :guest
            #end
        end

        # generate string that displays up or down arrows to indicate the rank of all other roles  
        # relative to the selected user's role
        def get_role_rank_string(user_role_index, given_role_index)
            unless user_role_index.is_a? Integer and user_role_index >= 0 and given_role_index.is_a? Integer and given_role_index >= 0
                return nil
            end

            rank_string = ""
            if user_role_index >= given_role_index
                rank = user_role_index - given_role_index
                if rank > 0
                    rank_string = "(#{'↑' * rank})"
                end
            else
                rank = given_role_index - user_role_index
                if rank > 0
                    rank_string = "(#{'↓' * rank})"
                end
            end

            rank_string
        end

        # check if the role selected by the user is within the list of possible roles allowed
        def is_selected_role_valid?(managed_roles, selected_role)
            # TODO sanity check params
            if managed_roles.include?(selected_role.to_sym) 
                return true
            else
                @user.errors.add(:role, "must be selected from the options given")
                return false
            end
        end

        def user_params
            params.require(:user).permit(:role)
        end
end

app/helpers/manage_users_helper.rb
module ManageUsersHelper
    # pretty-print role name
    def role_pretty_display(role)
        case role
        when Symbol
            role.to_s.sub("_", " ").capitalize
        when String
            role.sub("_", " ").capitalize
       end
    end
end

app/views/manage_users/_form.html.erb
<div id="user-role-form" class="col-md-8">
  <%= simple_form_for @user, url: urlpath, html: { class: "form-horizontal"}, wrapper: :horizontal_form_job  do |form| %>

    <div class="button-group">
      <%= form.button :submit, "Save record", class: "btn btn-primary" %>
      <%= link_to 'Go Back to User index', manage_users_path, class: 'btn btn-info' %>
    </div>

    <hr/>

    <% if @user.errors.any? %>
    <div class="panel panel-danger" id="error_explanation">
      <div class="panel-heading"><%= pluralize(@user.errors.count, "error") %> prohibited this User record from being updated:</div>
      <div class="panel-body">
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <% end %>

    <div class="form-group row string optional bibliography_year_published form-group-valid">
      <div class="col-sm-2 col-form-label-static">User email</div>
      <div class="col-sm-10 static-value"><%= @user.email %></div>
    </div>

    <div class="form-group row string optional bibliography_year_published form-group-valid">
      <div class="col-sm-2 col-form-label-static">User name</div>
      <div class="col-sm-10 static-value"><%= @user.name %></div>
    </div>

    <div class="form-group row string optional bibliography_year_published form-group-valid">
      <div class="col-sm-2 col-form-label-static">Current User role</div>
      <div class="col-sm-10 static-value"><%= @user.get_role_name %></div>
    </div>

    <%= form.input :role, 
        label: "New Role",
        collection: @role_options,
        prompt: "Select the new user role",
        hint: "(↓) indicates a lower ranked role for the user, and (↑) indicates a higher ranked role"
    %>

    <hr/>
    
    <div class="button-group">
      <%= form.button :submit, "Save record", class: "btn btn-primary" %>
      <%= link_to 'Go Back to Users index', manage_users_path, class: 'btn btn-info' %>
    </div>
  <% end %>
</div>

<div id="user-role-descriptions" class="col-md-4">
  <h3>Role descriptions</h3>
  <% @roles_current_user_can_manage.each do |role| %>
    <h4><%= role_pretty_display(role) %></h4>
    <p class="role-description"><%= @role_descriptions[role] %></p>
  <% end %>
</div>

app/views/manage_users/edit.html.erb
<% if @user.nil? %>
    <p>This record doesn't exist.</p>
    <%= link_to 'Go Back to Dashboard', dashboard_path %>
<% elsif can? :read, 'ManageUsers' %>

    <h2 class="edit-label"><span class="header-label">Editing User:</span> <%= @user.name.present? ? @user.name : @user.email %></h2>

    <%= render 'form', urlpath: manage_user_path %>
<% end %>

app/views/manage_users/index.html.erb
<div id="dashboard-users">
    <% if current_user.nil? %>
        <p>Sign in to access this portal.</p>
        <%= link_to new_user_session_path, class: 'login-button btn btn-primary' do %>Sign in<% end %>
        <%= link_to new_user_registration_path , class: 'login-button btn btn-primary' do %>Register<% end %>
    <% elsif can? :read, 'ManageUsers' %>
        <h2>User Management</h2>
        <h3>Update Users' roles</h3>

        <div class="top-message">
            <p>Your account allows you to manage users with the following role types*:<p>
            <ul class="list">
            <% @roles_current_user_can_manage.each do |role| %>
                <li><%= role_pretty_display(role) %></li>
            <% end %>
            </ul>
            <p>* 'Correspondent' is a synonym for 'Contributor'</p>
        </div>
        
        <div class="button-group">
            <%= link_to 'Go Back to Dashboard', dashboard_path, class: 'btn btn-info' %>
        </div>

        <div class="citations-list mine-list">
            <%= grid(@users_grid,
                show_filters: :when_filtered,
                allow_showing_all_records: false, 
                upper_pagination_panel: true
                ) do |user|

                user.column name: 'ID', attribute: 'id' do |u|
                    u.id
                end

                user.column name: 'Name', attribute: 'name' do |u|
                    u.name
                end

                user.column name: 'Email', attribute: 'email' do |u|
                    u.email
                end

                user.column name: 'Role', attribute: 'role'  do |u|
                    u.get_role_name
                end

                user.column name: 'Created At', attribute: 'created_at', filter: false do |u|
                    format_date_string(u.created_at)
                end

                user.column do |u|
                    "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', manage_user_path(u) )}</span></div>".html_safe + 
                    "<div class='icon edit-link'><span class='icon-link'>#{link_to( 'Edit', edit_manage_user_path(u) )}</span></div>".html_safe
                end

            end -%>

        <div class="button-group">
            <%= link_to 'Go Back to Dashboard', dashboard_path, class: 'btn btn-info' %>
        </div>

    <% else %>
        <%= render 'bibliographies/not_permitted' %>
    <% end %>
</div>

app/views/manage_users/show.html.erb
<% if @user.nil? %>
    <p>This record doesn't exist.</p>
    <%= link_to 'Go Back to Dashboard', dashboard_path %>
<% elsif can? :read, 'ManageUsers' %>
    <h2><%= @user.name.present? ? @user.name : @user.email %></h2>
    <div class="record-view">
        <div class="button-group">
            <%= link_to 'Edit this record', edit_manage_user_path(@user), class: 'btn btn-primary' %>
            <%= link_to 'Go Back to Users list', manage_users_path, class: 'btn btn-info' %>
        </div>

        <hr/>
        
        <div class="field-pair row">
            <label class="col-sm-2">User ID</label>
            <div class="field-value col-sm-10"><%= @user.id %></div>
        </div>

        <div class="field-pair row">
            <label class="col-sm-2">User name</label>
            <div class="field-value col-sm-10"><%= @user.name %></div>
        </div>

        <div class="field-pair row">
            <label class="col-sm-2">User email</label>
            <div class="field-value col-sm-10"><%= @user.email %></div>
        </div>

        <div class="field-pair row">
            <label class="col-sm-2">User role</label>
            <div class="field-value col-sm-10"><%= @user.get_role_name %></div>
        </div>

        <hr/>

        <div class="button-group">
            <%= link_to 'Edit this record', edit_manage_user_path(@user), class: 'btn btn-primary' %>
            <%= link_to 'Go Back to Users list', manage_users_path, class: 'btn btn-info' %>
        </div>
    </div>
<% end %>