config/routes.rb
Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  get "/dashboard/" => "dashboard#index"

  resources :manage_users, only: [:index, :show, :edit, :update], path: '/dashboard/users'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # custom path for displaying records created by signed-in user
  get '/citations/mine' => 'bibliographies#mine'

  # custom path for displaying records containing pending suggesitions
  get '/citations/terms/suggestions' => 'bibliographies#suggestions'

  # custom path for displaying all records
  # this is effectively the same as /citations  
  get '/citations/all' => 'bibliographies#index'

  # piggybacking on citationterms search controller for citation records
  get '/citations/search' => 'term_search#index'

  resources :staticpages

  get '/api/updated' => 'api#list_updated'
  get '/api/all' => 'api#all'

  get "/featuredrecords/all" => 'featuredrecords#load_all', as: 'featuredrecords_all'
  resources :featuredrecords

  namespace :about, path: '/about' do
    # root goes to dedicated home page record
    get "/" => '/staticpages#load_page', slug: :home, as: 'home_page'
    get "/:slug" => '/staticpages#load_page', as: 'page'
  end

  # get paths like "/citations/1"
  resources :bibliographies, path: '/citations' do
    root to: redirect('/citations/mine')
    resources :comments
    resources :standard_identifiers
    #resources :languages
    resources :reviewed_components
    resources :publishers
    resources :publish_places
    resources :dissertation_universities
    resources :series_multimedias
    resources :tags
    resources :subject_suggestions
    resources :location_suggestions
    resources :entity_suggestions
    resources :period_suggestions
    resources :language_suggestions
    resources :journal_suggestions
    resources :thesis_types_suggestions
    resources :authors
    resources :editors
    resources :book_editors
    resources :author_of_reviews
    resources :performers
    resources :bib, only: [:index], controller: "bib", action: "raw"
    resources :mla, only: [:index], controller: "bib", action: "mla"
    resources :chicago, only: [:index], controller: "bib", action: "chicago"
    resources :turabian, only: [:index], controller: "bib", action: "turabian"
  end

  # get paths like "/citations/terms/subject/1"
  namespace :citationterms, path: '/citations/terms' do
    resources :subjects, path: 'subjects' do
      get 'references', on: :member
    end
    resources :entities, path: 'jesuits' do
      get 'references', on: :member
    end
    resources :periods, path: 'centuries' do
      get 'references', on: :member
    end
    resources :locations, path: 'locations' do
      get 'references', on: :member
    end
    resources :languages, path: 'languages' do
      get 'references', on: :member
    end
    resources :people, path: 'people' do
      get 'references', on: :member
    end
    resources :journals, path: 'journals' do
      get 'references', on: :member
    end
    resources :thesis_types, path: 'thesis_types' do
      get 'references', on: :member
    end
    get 'search' => 'term_search#index'
  end

  get '/form_partial/:id/:reference_type' => 'bibliographies#form_partial'


  namespace :terms do
    root to: redirect('/')
    resources :entities, only: [:index], path: 'jesuits'
    resources :locations, only: [:index], path: 'locations'
    resources :subjects, only: [:index], path: 'subjects'
    resources :periods, only: [:index], path: 'centuries'
  end


  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  Blacklight::Marc.add_routes(self)
  # custom action for root
  # root to: "catalog#index"
  root to: "catalog#job_home"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end
  devise_for :users, controllers: { registrations: 'registrations' }
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_ajax_modal.html.erb
<div id="ajax-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal menu" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/shared/_bc_header.html.erb
<header class="header">
<div class="container-fluid">
<div class="">
            <div class="row">
              <div class="top-menu">
                <span class="upper hidden-xs"> <a href="https://www.bc.edu/iajs" class="iajs-link">Institute for Advanced Jesuit Studies</a> |
                  <a href="https://jesuitportal.bc.edu" target="new" class="portal-link">The Portal to Jesuit Studies</a>
                </span>
                <ul class="nav navbar-nav bc-top-nav ">
                  <% if has_user_authentication_provider? %>
                    <% if current_user %>
                      <li>
                        <div class='nav-item user-signout'><%= link_to 'Sign out', destroy_user_session_path %></div>
                      </li>
                      <% unless current_user.to_s.blank? -%>
                        <li>
                          <div class='nav-item user-email'><%= link_to current_user, edit_user_registration_path %></div>
                        </li>
                      <% end %>
                    <% else %>
                      <li>
                        <div class='nav-item user-signin'><%= link_to 'Sign in', new_user_session_path %></div>
                      </li>
                    <% end %>
                  <% end %>
                  
                </ul>
              </div>
            </div>
            <a class="hidden-xs" href="/">
              <div class="row brand-backgnd brand">
                <div class="header-brand center-col">
                  <div class="row">
                    <%= image_tag('job-banner-logo-white.png', alt: 'Jesuit Online Bibliography', class: 'logo') %>
                  </div>
                </div>
              </div>
            </a>
          </div>
</div>
</header>

app/views/shared/_bibliography_navbar.erb
<div id="header-navbar" class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--<%= link_to 'Jesuit Bibliography', dashboard_path, class: 'navbar-brand' %>-->
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <% if user_signed_in? and can? :read, 'Dashboard'%>
        <div class="navbar col-sm-12 center-col">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><%= link_to 'Search', root_path %></li>
                    <li><%= link_to 'Dashboard', dashboard_path %></li>
                    <li><%= link_to 'My Citations', citations_mine_path %></li>
                
                    <% if can? :manage, Bibliography %>
                    <li><%= link_to 'All Citations', citations_all_path %></li>
                    <% end %>

                    <% if can? :manage, 'Terms' %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Term lists <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <% if can? :read, Location %>
                            <li><%= link_to 'Where (Locations)', citationterms_locations_path %></li>
                            <% end %>

                            <% if can? :read, Period %>
                            <li><%= link_to 'When (Centuries)', citationterms_periods_path %></li>
                            <% end %>

                            <% if can? :read, Subject %>
                            <li><%= link_to 'What (Subjects)', citationterms_subjects_path %></li>
                            <% end %>

                            <% if can? :read, Entity %>
                            <li><%= link_to 'Who (Jesuits)', citationterms_entities_path %></li>
                            <% end %>

                            <% if can? :read, Language %>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to 'Languages', citationterms_languages_path %></li>
                            <% end %>

                            <% if can? :read, Journal %>
                            <li><%= link_to 'Journal Titles', citationterms_journals_path %></li>
                            <% end %>

                            <% if can? :read, Person %>
                            <li><%= link_to 'People', citationterms_people_path %></li>
                            <% end %>

                             <% if can? :read, ThesisType %>
                            <li><%= link_to 'Thesis Types', citationterms_thesis_types_path %></li>
                            <% end %>

                            <% if can? :manage, 'Suggestions' %>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to 'Pending Terms', citations_terms_suggestions_path %></li>
                            <% end %>
                        </ul>
                    </li>
                    <% end %>

                    <% if user_signed_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <% if current_user.admin_role? %>
                                <li>
                                    <%= link_to rails_admin_path, target: :_blank do %>
                                        Admin Panel <i class="fas fa-sm fa-external-link-alt"></i>
                                    <% end %>
                                </li>
                                <li role="separator" class="divider"></li>
                            <% end %>
                            <li>
                            <%= link_to dashboard_path do %>
                                <i class="fas fa-tachometer-alt"></i> Dashboard
                            <% end %>
                            </li>
                            <li>
                            <%= link_to blacklight_path do %>
                                <i class="fas fa-home"></i> Public search
                            <% end %>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to 'Logout', destroy_user_session_path %></li>
                        </ul>
                    </li>
                    <% end %>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div>
        <% end %>
    </div><!-- /.container-fluid -->
</div>

app/views/shared/_flash_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <div id="main-flashes">
      <%= yield %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bcfooter">
  <div class="footer container-fluid">
      <div class="row">
        <div class="inner center-col clearfix">
          <div class="pagebreak"></div>
          <div class='col-xs-12 col-sm-6 col-md-9 footer-text'>
            <p class="footer-title">Jesuit Online Bibliography</p>
            <p>The Jesuit Online Bibliography is organized by the <a href="/about">three founding institutions</a> &mdash; the Archivum Romanum Societatis Iesu, the Jesuitica Project at KU Leuven, and the Institute for Advanced Jesuit Studies at Boston College. The project's records are aggregated into the <a href="https://jesuitportal.bc.edu/">Portal to Jesuit Studies</a>.</p>
            <div id="order">
              <div class='col-xs-12 col-sm-6 col-md-3 logo'><%= image_tag('Logo_300.png', width:175, alt:'Boston College Libraries')%></div>
              <p id="lib-blurb">The Jesuit Online Bibliography was developed by the Boston College Libraries. Learn more about the <a style="text-decoration: underline;" href="/about/team">development team</a> and process.</p>
            </div>
          </div>
          <div class='col-xs-12 col-sm-12 col-md-12'>
            <ul class="site-links">
              <li><a href="/about/contact">Contact the Projects' Editors</a></li>
              <li><a href="/about">Learn More</a></li>
              <li><a href="/about/add-record">Add Your Records</a></li>
            </ul>
          </div>
          <div class='col-xs-12 col-sm-12 col-md-12 copyright'>
            <p>Copyright Trustees of Boston College</p>
          </div>
        </div>
      </div>
  </div>
 </footer>

app/views/shared/_header_navbar.html.erb
<div id="header-navbar" class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="<%= container_classes %>">
    <div class="navbar-header">
      <%= image_tag('job-banner-logo-white.png', alt: 'Jesuit Online Bibliography', class: 'logo') %>
      <button type="button" class="navbar-toggle btn collapsed" data-toggle="collapse" data-target="#user-util-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!--<%= link_to application_name, root_path, class: "navbar-brand" %>-->
    </div>

    <div class="collapse navbar-collapse" id="user-util-collapse">
      <%= render :partial=>'/user_util_links' %>
    </div>
  </div>
</div>

<div id="search-navbar" class="navbar navbar-default navbar-static-top col-sm-10 col-sm-offset-1" role="navigation">
  <div class="search-navbar-job col-sm-8 col-sm-offset-2 <%= container_classes %>">
    <div class="form-wrapper clearfix">
      <p id="search-title">Search the Jesuit Online Bibliography</p>
      <%= render_search_bar  %>
      <div class="search-links clearfix">
        <p id="search-help"><a href="/about/help">Help</a></p>
        <p id="advanced-search"><a href="/advanced">Advanced Search</a></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sitelinks_search_box.html.erb
<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
    "url": "<%= root_url %>",
    "potentialAction": {
      "@type": "SearchAction",
      "target": "<%= root_url %>?q={search_term_string}",
      "query-input": "required name=search_term_string"
    }
  }
</script>