config/routes.rb
Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  get "/dashboard/" => "dashboard#index"

  resources :manage_users, only: [:index, :show, :edit, :update], path: '/dashboard/users'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # custom path for displaying records created by signed-in user
  get '/citations/mine' => 'bibliographies#mine'

  # custom path for displaying records containing pending suggesitions
  get '/citations/terms/suggestions' => 'bibliographies#suggestions'

  # custom path for displaying all records
  # this is effectively the same as /citations  
  get '/citations/all' => 'bibliographies#index'

  # piggybacking on citationterms search controller for citation records
  get '/citations/search' => 'term_search#index'

  resources :staticpages

  get '/api/updated' => 'api#list_updated'
  get '/api/all' => 'api#all'

  get "/featuredrecords/all" => 'featuredrecords#load_all', as: 'featuredrecords_all'
  resources :featuredrecords

  namespace :about, path: '/about' do
    # root goes to dedicated home page record
    get "/" => '/staticpages#load_page', slug: :home, as: 'home_page'
    get "/:slug" => '/staticpages#load_page', as: 'page'
  end

  # get paths like "/citations/1"
  resources :bibliographies, path: '/citations' do
    root to: redirect('/citations/mine')
    resources :comments
    resources :standard_identifiers
    #resources :languages
    resources :reviewed_components
    resources :publishers
    resources :publish_places
    resources :dissertation_universities
    resources :series_multimedias
    resources :tags
    resources :subject_suggestions
    resources :location_suggestions
    resources :entity_suggestions
    resources :period_suggestions
    resources :language_suggestions
    resources :journal_suggestions
    resources :thesis_types_suggestions
    resources :authors
    resources :editors
    resources :book_editors
    resources :author_of_reviews
    resources :performers
    resources :bib, only: [:index], controller: "bib", action: "raw"
    resources :mla, only: [:index], controller: "bib", action: "mla"
    resources :chicago, only: [:index], controller: "bib", action: "chicago"
    resources :turabian, only: [:index], controller: "bib", action: "turabian"
  end

  # get paths like "/citations/terms/subject/1"
  namespace :citationterms, path: '/citations/terms' do
    resources :subjects, path: 'subjects' do
      get 'references', on: :member
    end
    resources :entities, path: 'jesuits' do
      get 'references', on: :member
    end
    resources :periods, path: 'centuries' do
      get 'references', on: :member
    end
    resources :locations, path: 'locations' do
      get 'references', on: :member
    end
    resources :languages, path: 'languages' do
      get 'references', on: :member
    end
    resources :people, path: 'people' do
      get 'references', on: :member
    end
    resources :journals, path: 'journals' do
      get 'references', on: :member
    end
    resources :thesis_types, path: 'thesis_types' do
      get 'references', on: :member
    end
    get 'search' => 'term_search#index'
  end

  get '/form_partial/:id/:reference_type' => 'bibliographies#form_partial'


  namespace :terms do
    root to: redirect('/')
    resources :entities, only: [:index], path: 'jesuits'
    resources :locations, only: [:index], path: 'locations'
    resources :subjects, only: [:index], path: 'subjects'
    resources :periods, only: [:index], path: 'centuries'
  end


  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  Blacklight::Marc.add_routes(self)
  # custom action for root
  # root to: "catalog#index"
  root to: "catalog#job_home"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end
  devise_for :users, controllers: { registrations: 'registrations' }
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/citationterms/entities_controller.rb
class Citationterms::EntitiesController < ApplicationController
    protect_from_forgery with: :exception
    #load_and_authorize_resource
 
    before_action :require_login
    before_action :authenticate_user!
    before_action :set_entity, only: [:show, :edit, :update, :destroy, :references]

    layout 'bibliography'

    def index
        authorize! :read, Entity, :message => "Unable to load this page."

        @entities_grid = initialize_grid(Entity, 
            order:           'entities.normal_name',
            order_direction: 'asc'
        )

        @entities = Entity.all
    end

    def show
    end

    def new
        @entity = Entity.new
    end

    def edit
    end

    def create
        @entity = Entity.new(entity_params)

        authorize! :create, @entity, :message => "Unable to create this Entity record."

        @entity.created_by = current_user

        @entity.sort_name = @entity.name

        @entity.display_name = @entity.name

        if @entity.save
            respond_to do |format|
                format.html { redirect_to citationterms_entity_path(@entity), notice: 'Entity was successfully created.' }
                format.json { render :show, status: :created, location: @entity }
            end
        else
            respond_to do |format|
                format.html { render :new }
                format.json { render json: @entity.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        authorize! :update, @entity, :message => "Unable to update this Entity record."

        # copy over subject_params into period_attributes so we can alter it
        entity_attributes = entity_params

        # update modified_by
        entity_attributes[:modified_by] = current_user

        # fill in sort_name, display_name if they are empty
        if entity_attributes[:sort_name].empty?
            entity_attributes[:sort_name] = @entity.name
        end
        #if entity_attributes[:display_name].empty?
        #    entity_attributes[:display_name] = @entity.name
        #end

        if @entity.update(entity_attributes)
            respond_to do |format|
                format.html { redirect_to citationterms_entity_path(@entity), notice: 'Entity was successfully updated.' }
                format.json { render :show, status: :ok, location: @entity }
            end
        else
            respond_to do |format|
                format.html { render :edit }
                format.json { render json: @entity.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        authorize! :destroy, @entity, :message => "Unable to destroy this Entity record."

        @entity.destroy
        respond_to do |format|
            format.html { redirect_to citationterms_entities_path, notice: 'Entity was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    def references
        @bibs_grid = initialize_grid(@entity.bib_refs) unless @entity.nil?
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_entity
            begin
                @entity = Entity.find(params[:id])
                authorize! :read, @entity, :message => "Unable to read this Entity record."
            rescue ActiveRecord::RecordNotFound => e
                @entity = nil
            end
        end

        def entity_params
            params.require(:entity).permit(:name, :sort_name, :display_name, :birth_date, :death_date)
        end
end

app/controllers/citationterms/journals_controller.rb
class Citationterms::JournalsController < ApplicationController
    protect_from_forgery with: :exception
    #load_and_authorize_resource
 
    before_action :require_login
    before_action :authenticate_user!
    before_action :set_journal, only: [:show, :edit, :update, :destroy, :references]

    layout 'bibliography'

    def index
        authorize! :read, Journal, :message => "Unable to load this page."

        @journals_grid = initialize_grid(Journal, 
            order:           'journals.normal_name',
            order_direction: 'asc'
        )

        @journals = Journal.all
    end

    def show
    end

    def new
        @journal = Journal.new
    end

    def edit
    end

    def create
        @journal = Journal.new(journal_params)

        authorize! :create, @journal, :message => "Unable to create this Journal record."

        @journal.created_by = current_user

        @journal.sort_name = @journal.name

        @journal.display_name = @journal.name

        if @journal.save
            respond_to do |format|
                format.html { redirect_to citationterms_journal_path(@journal), notice: 'Journal was successfully created.' }
                format.json { render :show, status: :created, location: @journal }
            end
        else
            respond_to do |format|
                format.html { render :new }
                format.json { render json: @journal.errors, status: :unprocessable_journal }
            end
        end
    end

    def update
        authorize! :update, @journal, :message => "Unable to update this Journal record."

        # copy over subject_params into period_attributes so we can alter it
        journal_attributes = journal_params

        # update modified_by
        journal_attributes[:modified_by] = current_user

        # fill in sort_name, display_name if they are empty
        if journal_attributes[:sort_name].empty?
            journal_attributes[:sort_name] = @journal.name
        end
        #if journal_attributes[:display_name].empty?
        #    journal_attributes[:display_name] = @journal.name
        #end

        if @journal.update(journal_attributes)
            respond_to do |format|
                format.html { redirect_to citationterms_journal_path(@journal), notice: 'Journal was successfully updated.' }
                format.json { render :show, status: :ok, location: @journal }
            end
        else
            respond_to do |format|
                format.html { render :edit }
                format.json { render json: @journal.errors, status: :unprocessable_journal }
            end
        end
    end

    def destroy
        authorize! :destroy, @journal, :message => "Unable to destroy this Journal record."

        @journal.destroy
        respond_to do |format|
            format.html { redirect_to citationterms_journals_path, notice: 'Journal was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    def references
        @bibs_grid = initialize_grid(@journal.bib_refs) unless @journal.nil?
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_journal
            begin
                @journal = Journal.find(params[:id])
                authorize! :read, @journal, :message => "Unable to read this Journal record."
            rescue ActiveRecord::RecordNotFound => e
                @journal = nil
            end
        end

        def journal_params
            params.require(:journal).permit(:name, :sort_name, :display_name)
        end
end

app/controllers/citationterms/languages_controller.rb
class Citationterms::LanguagesController < ApplicationController
    protect_from_forgery with: :exception
    #load_and_authorize_resource
 
    before_action :require_login
    before_action :authenticate_user!
    before_action :set_language, only: [:show, :edit, :update, :destroy, :references]

    layout 'bibliography'

    def index
        authorize! :read, Language, :message => "Unable to load this page."

        @languages_grid = initialize_grid(Language, 
            order:           'languages.normal_name',
            order_direction: 'asc'
        )

        @languages = Language.all
    end

    def show
    end

    def new
        @language = Language.new
    end

    def edit
    end

    def create
        @language = Language.new(language_params)

        authorize! :create, @language, :message => "Unable to create this Language record."

        @language.created_by = current_user

        if @language.save
            respond_to do |format|
                format.html { redirect_to citationterms_language_path(@language), notice: 'Language was successfully created.' }
                format.json { render :show, status: :created, location: @language }
            end
        else
            respond_to do |format|
                format.html { render :new }
                format.json { render json: @language.errors, status: :unprocessable_language }
            end
        end
    end

    def update
        authorize! :update, @language, :message => "Unable to update this Language record."

        # copy over subject_params into period_attributes so we can alter it
        language_attributes = language_params

        # update modified_by
        language_attributes[:modified_by] = current_user

        if @language.update(language_attributes)
            respond_to do |format|
                format.html { redirect_to citationterms_language_path(@language), notice: 'Language was successfully updated.' }
                format.json { render :show, status: :ok, location: @language }
            end
        else
            respond_to do |format|
                format.html { render :edit }
                format.json { render json: @language.errors, status: :unprocessable_language }
            end
        end
    end

    def destroy
        authorize! :destroy, @language, :message => "Unable to destroy this Language record."

        @language.destroy
        respond_to do |format|
            format.html { redirect_to citationterms_languages_path, notice: 'Language was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    def references
        @bibs_grid = initialize_grid(@language.bib_refs) unless @language.nil?
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_language
            begin
                @language = Language.find(params[:id])
                authorize! :read, @language, :message => "Unable to read this Language record."
            rescue ActiveRecord::RecordNotFound => e
                @language = nil
            end
        end

        def language_params
            params.require(:language).permit(:name)
        end
end

app/controllers/citationterms/term_search_controller.rb
class Citationterms::TermSearchController < ApplicationController
    protect_from_forgery with: :exception
    #load_and_authorize_resource

    before_action :require_login
    before_action :authenticate_user!

    CONTROLLED_VOCABS = {
      :subjects => Subject,
      :jesuits => Entity,
      :locations => Location,
      :journals => Journal,
      :languages => Language,
      :centuries => Period,
      :people => Person,
      :thesistypes => ThesisType
    }

    def index
        authorize! :create, Bibliography

        # Return an empty list if no proper type is specified
        @items = []

        # Controlled vocabulary types follow a normal format. Bibliographies are
        # a special case.
        type = params[:type].to_sym
        if controlled_vocab?(type)
            @items = search_controlled_vocabularies(type)
        elsif type === :bibliographies
            @items = search_bibliographies
        end

        respond_to do |format|
            format.json {
                render :json => @items
            }
        end
    end

    private

    # Do they want to search a controlled vocabulary?
    #
    # @param [Symbol] type
    # @return [TrueClass, FalseClass]
    def controlled_vocab?(type)
        CONTROLLED_VOCABS.key?(type)
    end

    # Search a controlled vocabulary
    #
    # @param [Symbol] type which vocabulary to search
    def search_controlled_vocabularies(type)
        ::ControlledVocabularyTermQuery.new(params, CONTROLLED_VOCABS[type]).perform
    end

    # Search bibliographies
    #
    def search_bibliographies
        citation_where_clause = "LOWER(display_title) LIKE LOWER(?)", "%#{params[:term]}%"
        Bibliography.where(citation_where_clause)
                   .order(:display_title)
                   .map { |item| {id: item.id, text: item.display_title + " (ID: #{item.id})"} }
    end
end

app/controllers/terms/locations_controller.rb
require "alphabetical_paginate"

class Terms::LocationsController < ApplicationController
    include Terms::ControllersHelper

    # use default Blacklight layout
    #layout 'bibliography'

    def index
        default_letter = "A"
        @letter = sanitize_letter(params[:letter], default_letter)

        @alpha_params_options = {
            bootstrap3: true,
            include_all: true,
            js: false
        }

        @locations, @alpha_params = Location
                        .order('normal_name')
                        .where.not(name: [nil, '']) # filter out nils and blanks
                        .alpha_paginate(@letter, @alpha_params_options) {|loc| loc.normal_name.downcase}
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/citationterms/locations/_error_messages.erb
<%# backend-based validation error details %>
<% if @location.present? and @location.errors.any? %>
  <div class="panel panel-danger error-panel" id="error_explanation">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@location.errors.count, "error") %> prohibited this record from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @location.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= render 'bibliographies/parsley_error_messages' %>

app/views/citationterms/locations/_form.html.erb
<%= simple_form_for @location, url: urlpath, html: { class: "form-horizontal"}, wrapper: :horizontal_form_job do |form| %>

  <div class="button-group">
    <%= form.button :submit, "Save record", class: "btn btn-primary" %>
    <%= link_to 'Cancel', citationterms_locations_path, class: 'btn btn-info' %>
  </div>
  
  <hr/>

  <%= form.input :name, 
      as: :string,
      required: true
  %>

  <%= form.input :sort_name, 
      as: :string,
      disabled: !@location.name.present?,
      placeholder: (!@location.name.present? ? BibliographyLocation::NAME_PLACEHOLDER : '') 
  %>

  <hr/>
  
  <div class="button-group">
    <%= form.button :submit, "Save record", class: "btn btn-primary" %>
    <%= link_to 'Cancel', citationterms_locations_path, class: 'btn btn-info' %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
    $('.simple_form').parsley().on('field:validated', function() {
        var ok = $('.parsley-error').length === 0;
        $('.bs-callout-info').toggleClass('hidden', !ok);
        $('.bs-callout-warning').toggleClass('hidden', ok);
    });
});
</script>

app/views/citationterms/locations/edit.html.erb
<% if @location.nil? %>
    <p>This record doesn't exist.</p>
    <%= link_to 'Go Back to Location Records index', citationterms_locations_path %>
<% elsif can? :edit, Location %>
    <h2 class="edit-label"><span class="header-label">Editing Location:</span> <%= @location.name %></h2>

    <%= render 'citationterms/update_alert', model_type: 'location', record: @location %>

    <%= render 'error_messages' %>

    <%= render 'form', urlpath: citationterms_location_path %>
    
    <%= render 'error_messages' %>
<% else %>
    <%= render 'bibliographies/not_permitted' %>
<% end %>

app/views/citationterms/locations/index.html.erb
<% if can? :read, Location %>
  <h2>Location terms index</h2>
  <p> Reminder: Do not use diacritics when filtering </p>

  <div class="button-group">
    <%= link_to 'Add New Location term', new_citationterms_location_path, class: 'btn btn-primary' %>
  </div>

  <%= grid(@locations_grid,
        show_filters: :when_filtered,
        allow_showing_all_records: false, 
        upper_pagination_panel: true
      ) do |g|

    g.column name: 'Name', attribute: 'normal_name' do |loc|
      loc.name
    end

    g.column name: 'Count' do |per|
      link_to per.bib_refs.count, references_citationterms_location_path(per.id)
    end

    g.column name: 'Last Modified At', attribute: 'updated_at', filter: false do |loc|
      format_date_string(loc.updated_at)
    end

    if can? :detroy, Location
      g.column do |loc|
        "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', citationterms_location_path(loc) )}</span></div>".html_safe + 
        "<div class='icon edit-link'><span class='icon-link'>#{link_to( 'Edit', edit_citationterms_location_path(loc) )}</span></div>".html_safe + 
        "<div class='icon destroy-link'><span class='icon-link'>#{link_to( 'Delete', citationterms_location_path(loc), method: :delete, data: { confirm: 'Are you sure?' } )}</span></div>".html_safe
      end
    elsif can? :edit, Location
      g.column do |loc|
        "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', citationterms_location_path(loc) )}</span></div>".html_safe + 
        "<div class='icon edit-link'><span class='icon-link'>#{link_to( 'Edit', edit_citationterms_location_path(loc) )}</span></div>".html_safe
      end
    else
      g.column do |loc|
        "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', citationterms_location_path(loc) )}</span></div>".html_safe
      end
    end
  end -%>
  
  <div class="button-group">
    <%= link_to 'Add New Location term', new_citationterms_location_path, class: 'btn btn-primary' %>
  </div>

<% else %>
  <%= render 'bibliographies/not_permitted' %>
<% end %>

app/views/citationterms/locations/new.html.erb
<h2>Add New Location Term</h2>

<% if can? :create, Location %>
    <%= render 'error_messages' %>

    <%= render 'form', urlpath: citationterms_locations_path %>

    <%= render 'error_messages' %>
<% else %>
  <%= render 'bibliographies/not_permitted' %>
<% end %>

app/views/citationterms/locations/references.html.erb
<% if @location.nil? %>
    <p>This record doesn't exist.</p>
    <%= link_to 'Go Back to Location terms index', citationterms_locations_path %>
<% elsif can? :read, Location %>
    <h2>Citation references for: <%= @location.name.present? ? @location.name : @location.id %></h2>

    <div class="button-group">
        <%= link_to 'Go Back to Location Record', citationterms_location_path(@location), class: 'btn btn-primary' %>
        <%= link_to 'Go Back to Location Terms index', citationterms_locations_path, class: 'btn btn-info' %>
    </div>

    <div class="citations-list all-list">
        <% if @location.bib_refs.present? %>
            <h4>The following <%= pluralize(@location.bib_refs.count, 'Citation record') %> reference this Location record</h4>
            <%= grid(@bibs_grid,
                show_filters: :when_filtered,
                allow_showing_all_records: false, 
                upper_pagination_panel: true
                ) do |g|

                g.column name: 'ID', attribute: 'id' do |bib|
                    bib.id
                end

                g.column name: 'Format', attribute: 'reference_type', custom_filter: :auto

                g.column name: 'Title', attribute: 'display_title' do |bib|
                    if bib.display_title.present?
                    bib.display_title.html_safe
                    else
                    Bibliography::NO_DISPLAY_TITLE
                    end
                end

                g.column name: 'Author(s)', attribute: 'display_author', ordering: false do |bib|
                    if bib.display_author.present?
                    out = "".html_safe
                    bib.display_author.split('|').each do |author|
                        out << "<span class='value-part'>#{author}</span>".html_safe
                    end
                    out
                    else
                    Bibliography::NO_DISPLAY_AUTHOR
                    end
                end

                g.column name: 'Status', attribute: 'status', custom_filter: :auto do |bib|
                    if bib.status.present?
                        "<span class='badge badge-#{bib.status}'>#{bib.status.capitalize}</span>".html_safe
                    end
                end

                g.column name: 'Created by', attribute: 'created_by'

                #g.column name: 'Created At', attribute: 'created_at', filter: false do |bib|
                #  format_date_string(bib.created_at)
                #end

                g.column name: 'Last Modified', attribute: 'updated_at', filter: false do |bib|
                    format_date_string(bib.updated_at)
                end

                if can? :detroy, Bibliography
                    g.column do |bib|
                    "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', bibliography_path(bib) )}</span></div>".html_safe + 
                    "<div class='icon edit-link'><span class='icon-link'>#{link_to( 'Edit', edit_bibliography_path(bib) )}</span></div>".html_safe + 
                    "<div class='icon destroy-link'><span class='icon-link'>#{link_to( 'Delete', bibliography_path(bib), method: :delete, data: { confirm: 'Are you sure?' } )}</span></div>".html_safe
                    end
                elsif can? :edit, Bibliography
                    g.column do |bib|
                    "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', bibliography_path(bib) )}</span></div>".html_safe + 
                    "<div class='icon edit-link'><span class='icon-link'>#{link_to( 'Edit', edit_bibliography_path(bib) )}</span></div>".html_safe
                    end
                else
                    g.column do |bib|
                    "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', bibliography_path(bib) )}</span></div>".html_safe
                    end
                end
            end -%>
        <% else %>
            <h4>There are no Citation records that reference this Location record</h4>
        <% end %>
    </div>

    <div class="button-group">
        <%= link_to 'Go Back to Location Record', citationterms_location_path(@location), class: 'btn btn-primary' %>
        <%= link_to 'Go Back to Location Terms index', citationterms_locations_path, class: 'btn btn-info' %>
    </div>

<% else %>
    <%= render 'bibliographies/not_permitted' %>
<% end %>

app/views/citationterms/locations/show.html.erb
<% if @location.nil? %>
    <p>This record doesn't exist.</p>
    <%= link_to 'Go Back to Location Terms index', citationterms_location_path %>
<% elsif can? :read, Location %>
    <h2><%= @location.name.present? ? @location.name : @location.id %></h2>

    <div class="record-view">
        <div class="button-group">
            <% if can? :update, Location %>
            <%= link_to 'Edit this record', edit_citationterms_location_path(@location), class: 'btn btn-primary' %>
            <% end %>
            <%= link_to 'View citation references', references_citationterms_location_path(@location), class: 'btn btn-warning' %>
            <%= link_to 'Go Back to Location terms index', citationterms_locations_path, class: 'btn btn-info' %>
        </div>
        
        <div class="record-view-fields">
            <div class="locations-list col-sm-12">
                <h4>Fields</h4>

                <div class="field-pair row">
                    <label class="col-sm-2">Location Name</label>
                    <div class="field-value col-sm-10"><%= @location.name %></div>
                </div>

                <div class="field-pair row">
                    <label class="col-sm-2">Location Sort Name</label>
                    <div class="field-value col-sm-10"><%= @location.sort_name %></div>
                </div>
            </div>

            <%= render 'citationterms/metadata', record: @location %>
        </div>

        <div class="button-group">
            <% if can? :update, Location %>
            <%= link_to 'Edit this record', edit_citationterms_location_path(@location), class: 'btn btn-primary' %>
            <% end %>
            <%= link_to 'View citation references', references_citationterms_location_path(@location), class: 'btn btn-warning' %>
            <%= link_to 'Go Back to Location terms index', citationterms_locations_path, class: 'btn btn-info' %>
        </div>
    </div>
<% else %>
    <%= render 'bibliographies/not_permitted' %>
<% end %>