config/routes.rb
Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  get "/dashboard/" => "dashboard#index"

  resources :manage_users, only: [:index, :show, :edit, :update], path: '/dashboard/users'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # custom path for displaying records created by signed-in user
  get '/citations/mine' => 'bibliographies#mine'

  # custom path for displaying records containing pending suggesitions
  get '/citations/terms/suggestions' => 'bibliographies#suggestions'

  # custom path for displaying all records
  # this is effectively the same as /citations  
  get '/citations/all' => 'bibliographies#index'

  # piggybacking on citationterms search controller for citation records
  get '/citations/search' => 'term_search#index'

  resources :staticpages

  get '/api/updated' => 'api#list_updated'
  get '/api/all' => 'api#all'

  get "/featuredrecords/all" => 'featuredrecords#load_all', as: 'featuredrecords_all'
  resources :featuredrecords

  namespace :about, path: '/about' do
    # root goes to dedicated home page record
    get "/" => '/staticpages#load_page', slug: :home, as: 'home_page'
    get "/:slug" => '/staticpages#load_page', as: 'page'
  end

  # get paths like "/citations/1"
  resources :bibliographies, path: '/citations' do
    root to: redirect('/citations/mine')
    resources :comments
    resources :standard_identifiers
    #resources :languages
    resources :reviewed_components
    resources :publishers
    resources :publish_places
    resources :dissertation_universities
    resources :series_multimedias
    resources :tags
    resources :subject_suggestions
    resources :location_suggestions
    resources :entity_suggestions
    resources :period_suggestions
    resources :language_suggestions
    resources :journal_suggestions
    resources :thesis_types_suggestions
    resources :authors
    resources :editors
    resources :book_editors
    resources :author_of_reviews
    resources :performers
    resources :bib, only: [:index], controller: "bib", action: "raw"
    resources :mla, only: [:index], controller: "bib", action: "mla"
    resources :chicago, only: [:index], controller: "bib", action: "chicago"
    resources :turabian, only: [:index], controller: "bib", action: "turabian"
  end

  # get paths like "/citations/terms/subject/1"
  namespace :citationterms, path: '/citations/terms' do
    resources :subjects, path: 'subjects' do
      get 'references', on: :member
    end
    resources :entities, path: 'jesuits' do
      get 'references', on: :member
    end
    resources :periods, path: 'centuries' do
      get 'references', on: :member
    end
    resources :locations, path: 'locations' do
      get 'references', on: :member
    end
    resources :languages, path: 'languages' do
      get 'references', on: :member
    end
    resources :people, path: 'people' do
      get 'references', on: :member
    end
    resources :journals, path: 'journals' do
      get 'references', on: :member
    end
    resources :thesis_types, path: 'thesis_types' do
      get 'references', on: :member
    end
    get 'search' => 'term_search#index'
  end

  get '/form_partial/:id/:reference_type' => 'bibliographies#form_partial'


  namespace :terms do
    root to: redirect('/')
    resources :entities, only: [:index], path: 'jesuits'
    resources :locations, only: [:index], path: 'locations'
    resources :subjects, only: [:index], path: 'subjects'
    resources :periods, only: [:index], path: 'centuries'
  end


  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  Blacklight::Marc.add_routes(self)
  # custom action for root
  # root to: "catalog#index"
  root to: "catalog#job_home"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable

  end
  devise_for :users, controllers: { registrations: 'registrations' }
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/featuredrecord.rb
class Featuredrecord < ApplicationRecord
    belongs_to :bibliography, optional: true

    validates :name, presence: true
    validates :rank, presence: true

    def isbns
        if bibliography.present?
            unless bibliography.isbns.empty?
                return bibliography.isbns.map {|isbn| isbn.value}
            end
        end
        []
    end

    def issns
        if bibliography.present?
            unless bibliography.isbns.empty?
                return bibliography.isbns.map {|issn| issn.value}
            end
        end
        []
    end
end

app/controllers/featuredrecords_controller.rb
require 'net/http'

class FeaturedrecordsController < ApplicationController
    protect_from_forgery with: :exception
    #load_and_authorize_resource

    #before_action :require_login
    #before_action :authenticate_user!
    before_action :set_featuredrecord, only: [:show, :edit, :update, :destroy]

    layout 'bibliography'

    def index
        authorize! :read, Featuredrecord, :message => "Unable to load this record."

        @records_grid = initialize_grid(Featuredrecord,
            order:           'featuredrecords.rank',
            order_direction: 'desc'
        )

        @records = Featuredrecord.all
    end

    def show
    end

    def load_all
        @records = Featuredrecord.where(published: :true).order(rank: :desc)

        out_html = "<div id='all-featured-records'>"
        out_json = []
        @records.each do |record|
            out_html << "<div class='featured-record' data-record-rank='#{record.rank}' data-bibliography-id='#{record.bibliography_id}' id='#{record.id}'>#{record.body}</div>"
            out_json << {
                id: record.id,
                rank: record.rank,
                bib_id: record.bibliography_id,
                body: record.body
            }
        end
        out_html << "</div>"

        respond_to do |format|
            format.html { render body: out_html }
            format.json  { render body: out_json.to_json }
        end

    end

    def new
        @record = Featuredrecord.new
    end

    def edit
    end

    def create
        @record = Featuredrecord.new(featuredrecord_params)

        authorize! :create, @record, :message => "Unable to create this Featured record."

        @record.created_by = current_user
        @record.image = set_image

        if @record.save
            respond_to do |format|
                format.html { redirect_to featuredrecord_path(@record), notice: 'Featured Record was successfully created.' }
                format.json { render :show, status: :created, location: @record }
            end
        else
            respond_to do |format|
                format.html { render :new }
                format.json { render json: @record.errors, status: :unprocessable_featuredrecord }
            end
        end
    end

    def update
        authorize! :update, @record, :message => "Unable to update this Featured record."

        # copy over subject_params into period_attributes so we can alter it
        record_attributes = featuredrecord_params

        # update modified_by
        record_attributes[:modified_by] = current_user

        @record.image = set_image

        if @record.update(record_attributes)
            respond_to do |format|
                format.html { redirect_to featuredrecord_path(@record), notice: 'Featured record was successfully updated.' }
                format.json { render :show, status: :ok, location: @record }
            end
        else
            respond_to do |format|
                format.html { render :edit }
                format.json { render json: @record.errors, status: :unprocessable_featuredrecord }
            end
        end
    end

    def destroy
        authorize! :destroy, @record, :message => "Unable to destroy this Featured record."

        @record.destroy
        respond_to do |format|
            format.html { redirect_to featuredrecords_path, notice: 'Featured record was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_featuredrecord
            begin
                @record = Featuredrecord.find(params[:id])
                authorize! :read, @record, :message => "Unable to read this Page record."
            rescue ActiveRecord::RecordNotFound => e
                @record = nil
                @bib = nil
            else
                # pull in referenced Bibliography record
                fetch_related_record
            end
        end

        def featuredrecord_params
            params.require(:featuredrecord).permit(:name, :rank, :published, :body, :bibliography_id)
        end

        def fetch_related_record
            if @record.bibliography_id.present?
                begin
                    @bib = @record.bibliography
                rescue ActiveRecord::RecordNotFound => e
                    @bib.nil
                end
            else
                @bib = nil
            end
        end

        # Iterate through ISBNs and ISSNs looking for a valid Syndetic cover image
        def set_image
            @record.isbns.each do |isbn|
                url = book_cover_url(isbn: isbn)
                if valid_cover_image?(url)
                    return url
                end
            end

            @record.issns.each do |issn|
                url = book_cover_url(issn: issn)
                if valid_cover_image?(url)
                    return url
                end
            end

            nil
        end

        # If he URL returns an image bigger than 1kb we will consider it valid
        def valid_cover_image?(url)
            uri = URI(url)
            return (Net::HTTP.get(uri).bytesize > 1200)
        end

        def book_cover_url(isbn: nil, issn: nil)
            base = 'https://proxy-na.hosted.exlibrisgroup.com/exl_rewrite/syndetics.com/index.aspx'

            params = {:client => 'bostonh'}
            if (isbn)
                params[:isbn] = "#{isbn}/MC.jpg"
            elsif (issn)
                params[:issn] = "#{issn}/MC.jpg"
            end

            "#{base}?#{params.to_query}"
        end
end

app/helpers/featuredrecords_helper.rb
module FeaturedrecordsHelper
    def get_featured_records
        Featuredrecord.where(published: :true).order('featuredrecords.rank DESC').all
    end
end

app/views/featuredrecords/_error_messages.erb
<%# backend-based validation error details %>
<% if @record.present? and @record.errors.any? %>
  <div class="panel panel-danger error-panel" id="error_explanation">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
        <% @record.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= render 'bibliographies/parsley_error_messages' %>

app/views/featuredrecords/_form.html.erb
<%= simple_form_for @record, url: urlpath, html: { class: "form-horizontal"}, wrapper: :horizontal_form_job do |form| %>

  <div class="button-group">
    <%= form.button :submit, "Save record", class: "btn btn-primary" %>
    <%= link_to 'Go Back to Featured records index', featuredrecords_path, class: 'btn btn-info' %>
  </div>

  <hr/>

  <%= form.input :published,
      label: 'Make published?',
      as: :boolean
  %>

  <%= form.input :name, 
      as: :string,
      required: true,
      hint: 'Give a name for this featured record. This is used for internal management'
  %>

  <%= form.input :rank, 
      as: :string,
      required: true,
      hint: 'How this record will be sorted in the Featured Record box. For example, a rank of 100 will appear earlier on a list than a rank of 10'
  %>

  <%#= form.input :bibliography_id,
      label: 'Related record ID',
      as: :integer,
      hint: 'Add in the ID of the record you\'d like to connect with'
  %>

  <div class="row string optional referenced-citation-record">
    <label class="col-sm-2 col-form-label string optional">Referenced Citation record</label>
    <div class="col-sm-10">
        <div class="">
            <%= form.association :bibliography, 
              label: false,
              # make sure that we pull the display_title field as the collection label
              label_method: Proc.new { |b| b.display_title if b.present? },
              collection: [@bib],
              #prompt: 'Select a Citation record to reference',
              hint: 'Search for the Citation record you want to link to this Featured Record',
              input_html: {
                  class: 'bibliographies',
                  "data-url": citationterms_search_path
              }
            %>
        </div>
        <div class="referenced_citation_record_parent"></div>
    </div>
  </div>

  <script>
  $(document).ready(function() {
      function generate_settings(){
          additional_settings = {
              dropdownParent: $(".referenced_citation_record_parent")
          }
          settings = select2_config(".bibliographies", "bibliographies");

          return $.extend(settings, additional_settings);
      }
      $('.bibliographies').select2( generate_settings() );
  });
  </script>

  <div class="form-group row string optional featuredrecord_body form-group-valid">
    <label class="col-sm-2 col-form-label select">Body</label>
    <div class="col-sm-10">
        <%= form.text_area :body, 
            label: 'body', 
            class: "tinymce",
            rows: 20
            # has id: 'featuredrecord_body'
        %>
        <%= tinymce :pages, selector: "#featuredrecord_body" %>
    </div>
  </div>

  <hr/>
  
  <div class="button-group">
    <%= form.button :submit, "Save record", class: "btn btn-primary" %>
    <%= link_to 'Go Back to Static Pages index', staticpages_path, class: 'btn btn-info' %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
    $('.simple_form').parsley().on('field:validated', function() {
        var ok = $('.parsley-error').length === 0;
        $('.bs-callout-info').toggleClass('hidden', !ok);
        $('.bs-callout-warning').toggleClass('hidden', ok);
    });
});
</script>

app/views/featuredrecords/edit.html.erb
<% if @record.nil? %>
    <p>This record doesn't exist.</p>
    <%= link_to 'Go Back to Featured Records index', staticpages_path, class: 'btn btn-info' %>
<% elsif can? :edit, Featuredrecord %>
    <h2 class="edit-label"><span class="header-label">Editing Featured Record:</span> <%= @record.name.present? ? @record.name : @record.id %></h2>

    <%= render 'error_messages' %>

    <%= render 'form', urlpath: featuredrecord_path %>

    <%= render 'error_messages' %>
<% else %>
    <%= render 'bibliographies/not_permitted' %>
<% end %>

app/views/featuredrecords/index.html.erb
<% if can? :read, Featuredrecord %>
  <h2>Featured Records index</h2>

  <%# don't allow the user to add new static pages from this view %>
  <div class="button-group">
    <%= link_to 'Add New Featured Record', new_featuredrecord_path, class: 'btn btn-primary' %>
  </div>

  <%= grid(@records_grid,
        show_filters: :when_filtered,
        allow_showing_all_records: false, 
        upper_pagination_panel: true
      ) do |g|

    g.column name: 'Name', attribute: 'name'

    g.column name: 'List Rank', attribute: 'rank'

    g.column name: 'Published', attribute: 'published'

    g.column name: 'Linked record', attribute: 'bibliography_id' do |record|
      if record.bibliography.present? and record.bibliography.id.present?
        linked_record = Bibliography.find_by_id(record.bibliography.id)
        if linked_record.present?
          link_to linked_record.display_title, bibliography_path(record.bibliography.id), target: '_blank'
        else
          "<em>Can't find record with ID ##{record.bibliography.id}</em>".html_safe
        end
      else
        "<em>none</em>".html_safe
      end
    end

    g.column name: 'Last Modified At', attribute: 'updated_at', filter: false do |record|
      format_date_string(record.updated_at)
    end

    if can? :destroy, Featuredrecord
      g.column do |record|
        "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', featuredrecord_path(record) )}</span></div>".html_safe + 
        "<div class='icon edit-link'><span class='icon-link'>#{link_to( 'Edit', edit_featuredrecord_path(record) )}</span></div>".html_safe + 
        "<div class='icon destroy-link'><span class='icon-link'>#{link_to( 'Delete', featuredrecord_path(record), method: :delete, data: { confirm: 'Are you sure?' } )}</span></div>".html_safe
      end
    elsif can? :edit, Featuredrecord
      g.column do |record|
        "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', featuredrecord_path(record) )}</span></div>".html_safe + 
        "<div class='icon edit-link'><span class='icon-link'>#{link_to( 'Edit', edit_featuredrecord_path(record) )}</span></div>".html_safe
      end
    else
      g.column do |record|
        "<div class='icon show-link'><span class='icon-link'>#{link_to( 'Show', featuredrecord_path(record) )}</span></div>".html_safe
      end
    end
  end -%>

  <%# don't allow the user to add new static pages from this view %>
  <div class="button-group">
    <%= link_to 'Add New Featured Record', new_featuredrecord_path, class: 'btn btn-primary' %>
  </div>

<% else %>
  <%= render 'bibliographies/not_permitted' %>
<% end %>

app/views/featuredrecords/load_all.html.erb
<div id="all-featured-records">
<% @records.each do |record| %>
    <div class="featured-record-body" id="<%= record.id %>">
        <%= record.body.html_safe %>
    </div>
<% end %>
</div>

app/views/featuredrecords/new.html.erb
<h2>Add New Featured Record</h2>

<% if can? :create, Featuredrecord %>
    <%= render 'error_messages' %>

    <%= render 'form', urlpath: featuredrecords_path %>

    <%= render 'error_messages' %>
<% else %>
  <%= render 'bibliographies/not_permitted' %>
<% end %>

app/views/featuredrecords/show.html.erb
<% if @record.nil? %>
    <p>This page doesn't exist.</p>
    <%= link_to 'Go Back to Featured Records index', featuredrecords_path %>
<% elsif can? :read, Featuredrecord %>
    <div class="record-view">
        <div class="button-group">
            <% if can? :update, Featuredrecord %>
            <%= link_to 'Edit this Featured Record', edit_featuredrecord_path(@record), class: 'btn btn-primary' %>
            <% end %>
            <%= link_to 'Go Back to Featured Record index', featuredrecords_path, class: 'btn btn-info' %>
        </div>

        <hr/>
        
        <div class="clearfix">
            <div class="fields-list col-sm-12">
                <h4>Fields</h4>

                <% if @record.name.present? %>
                    <div class="field-pair row">
                        <label class="col-sm-4">Featured Record</label>
                        <div class="field-value col-sm-8"><%= @record.name %></div>
                    </div>
                <% end %>

                <% if @record.rank.present? %>
                    <div class="field-pair row">
                        <label class="col-sm-4">Featured Record rank</label>
                        <div class="field-value col-sm-8"><%= @record.rank %></div>
                    </div>
                <% end %>

                <% if @record.published.present? %>
                    <div class="field-pair row">
                        <label class="col-sm-4">Publish in the Featured Record box?</label>
                        <div class="field-value col-sm-8"><%= @record.published %></div>
                    </div>
                <% end %>

                <% if @record.bibliography_id.present? and @bib.present? %>
                    <div class="field-pair row">
                        <label class="col-sm-4">Related Record ID</label>
                        <div class="field-value col-sm-8"><%= @record.bibliography_id %></div>
                    </div>
                    <div class="field-pair row">
                        <label class="col-sm-4">Related Record name (read only)</label>
                        <div class="field-value col-sm-8"><%= @bib.display_title %></div>
                    </div>
                <% end %>

                <div class="field-pair row">
                    <label class="col-sm-4">Body</label>
                    <div class="field-value col-sm-8"><%= @record.body.html_safe %></div>
                </div>
            </div>

            <div class="citations-list col-sm-12">
                <hr/>

                <h4>Metadata</h4>

                <div class="field-pair row">
                    <label class="col-sm-2">Created By</label>
                    <div class="field-value col-sm-10"><%= @record.created_by %></div>
                </div>

                <div class="field-pair row">
                    <label class="col-sm-2">Created At</label>
                    <div class="field-value col-sm-10"><%= format_date_string(@record.created_at) %></div>
                </div>

                <% if @record.modified_by.present? and can? :read, Featuredrecord %>
                <div class="field-pair row">
                    <label class="col-sm-2">Last Modified By</label>
                    <div class="field-value col-sm-10"><%= @record.modified_by %></div>
                </div>
                <% end %>

                <% if @record.updated_at.present? and can? :read, Featuredrecord %>
                <div class="field-pair row">
                    <label class="col-sm-2">Last Modified At</label>
                    <div class="field-value col-sm-10"><%= format_date_string(@record.updated_at) %></div>
                </div>
                <% end %>
            </div>
        </div>

        <hr/>

        <div class="button-group">
            <% if can? :update, Featuredrecord %>
            <%= link_to 'Edit this Featured Record', edit_featuredrecord_path(@record), class: 'btn btn-primary' %>
            <% end %>
            <%= link_to 'Go Back to Featured Record index', featuredrecords_path, class: 'btn btn-info' %>
        </div>
    </div>
<% else %>
    <%= render 'bibliographies/not_permitted' %>
<% end %>